# Generated by Django 2.1.5 on 2019-02-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_modeldefinition.dynamicclass_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'dynamic classes',
            },
        ),
        migrations.CreateModel(
            name='DynamicObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.DynamicClass')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('constraint', models.CharField(choices=[('required', 'required'), ('optional', 'optional'), ('result', 'result')], default='required', max_length=100)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'modeldefinition'), ('model__startswith', 'value'), models.Q(('app_label', 'modeldefinition'), ('model', 'value'), _negated=True)), on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contenttypes.ContentType')),
                ('dynamic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='modeldefinition.DynamicClass')),
            ],
            options={
                'ordering': ('name', 'dynamic_class'),
            },
        ),
        migrations.CreateModel(
            name='ValueNumber',
            fields=[
                ('abstractvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.AbstractValue')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.abstractvalue',),
        ),
        migrations.CreateModel(
            name='ValuePointer',
            fields=[
                ('abstractvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.AbstractValue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.abstractvalue',),
        ),
        migrations.CreateModel(
            name='ValueString',
            fields=[
                ('abstractvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.AbstractValue')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.abstractvalue',),
        ),
        migrations.AddField(
            model_name='dynamicobject',
            name='elements',
            field=models.ManyToManyField(through='modeldefinition.AbstractValue', to='modeldefinition.Field'),
        ),
        migrations.AddField(
            model_name='abstractvalue',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.DynamicObject'),
        ),
        migrations.AddField(
            model_name='abstractvalue',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modeldefinition.Field'),
        ),
        migrations.AddField(
            model_name='abstractvalue',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_modeldefinition.abstractvalue_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='valuepointer',
            name='value_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuepointers', to='modeldefinition.DynamicObject'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['dynamic_class', 'name'], name='modeldefini_dynamic_103246_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'dynamic_class')},
        ),
        migrations.AlterUniqueTogether(
            name='abstractvalue',
            unique_together={('element', 'field')},
        ),
    ]
