# Generated by Django 2.1.5 on 2019-01-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueObject',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.Value')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.DynamicObject')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.value',),
        ),
    ]
