# Generated by Django 2.1.5 on 2019-01-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTemplateTasks',
            new_name='JobTemplateTask',
        ),
        migrations.RenameModel(
            old_name='TaskParameters',
            new_name='TaskParameter',
        ),
    ]
