# Generated by Django 2.1.5 on 2019-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0002_valueobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicclass',
            name='related',
            field=models.ManyToManyField(related_name='_dynamicclass_related_+', to='modeldefinition.DynamicClass'),
        ),
    ]
