# Generated by Django 2.1.7 on 2019-03-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0002_auto_20190325_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('name', 'element')},
        ),
    ]
