# Generated by Django 2.1.5 on 2019-01-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0002_auto_20190112_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfield',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='object_id',
        ),
    ]
