# Generated by Django 2.1.5 on 2019-03-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0002_auto_20190201_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('Namespace', 'Namespace'), ('Class', 'Class'), ('Object', 'Object')], default='Object', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='modeldefinition.Element')),
            ],
            options={
                'ordering': ('parent', 'name'),
            },
        ),
    ]
