# Generated by Django 2.1.7 on 2019-03-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0003_auto_20190325_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueObject',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.Property')),
                ('value', models.ForeignKey(limit_choices_to=models.Q(model_type='Object'), on_delete=django.db.models.deletion.CASCADE, related_name='object_set', to='modeldefinition.Element')),
                ('value_class', models.ForeignKey(limit_choices_to=models.Q(model_type='Class'), on_delete=django.db.models.deletion.CASCADE, related_name='class_set', to='modeldefinition.Element')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.property',),
        ),
    ]
