# Generated by Django 2.1.5 on 2019-01-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0003_auto_20190112_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.CustomField')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.AbstractValue')),
            ],
        ),
    ]
