# Generated by Django 2.1.7 on 2019-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0003_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='modeldefinition.Element'),
        ),
    ]
