# Generated by Django 2.1.5 on 2019-01-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0004_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractvalue',
            name='field',
        ),
    ]
