# Generated by Django 2.1.7 on 2019-03-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modeldefinition', '0005_auto_20190312_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('app_label', 'modeldefinition'), ('model__startswith', 'value'), models.Q(('app_label', 'modeldefinition'), ('model', 'value'), _negated=True)), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
