# Generated by Django 2.1.7 on 2019-03-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0004_valueobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueObjectMultiple',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modeldefinition.Property')),
                ('value', models.ManyToManyField(limit_choices_to=models.Q(model_type='Object'), related_name='objects_set', to='modeldefinition.Element')),
                ('value_class', models.ForeignKey(limit_choices_to=models.Q(model_type='Class'), on_delete=django.db.models.deletion.CASCADE, related_name='classes_set', to='modeldefinition.Element')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('modeldefinition.property',),
        ),
    ]
