# Generated by Django 2.1.7 on 2019-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0006_valueobjectmultiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuenumber',
            name='formatting',
            field=models.CharField(default='{:.2f}', max_length=100),
        ),
    ]
