# Generated by Django 2.1.7 on 2019-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0006_property_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
    ]
