# Generated by Django 2.1.5 on 2019-01-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0006_auto_20190116_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.CustomField')),
            ],
        ),
        migrations.RemoveField(
            model_name='namespace',
            name='records',
        ),
        migrations.RemoveField(
            model_name='record',
            name='field',
        ),
        migrations.RemoveField(
            model_name='record',
            name='value',
        ),
        migrations.AddField(
            model_name='keyvaluepair',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.Record'),
        ),
        migrations.AddField(
            model_name='keyvaluepair',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.AbstractValue'),
        ),
        migrations.AddField(
            model_name='record',
            name='values',
            field=models.ManyToManyField(through='modeldefinition.KeyValuePair', to='modeldefinition.CustomField'),
        ),
    ]
