# Generated by Django 2.1.5 on 2019-01-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0007_auto_20190116_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='field',
        ),
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='record',
        ),
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='value',
        ),
        migrations.AddField(
            model_name='abstractvalue',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.CustomField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractvalue',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modeldefinition.Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='values',
            field=models.ManyToManyField(through='modeldefinition.AbstractValue', to='modeldefinition.CustomField'),
        ),
        migrations.DeleteModel(
            name='KeyValuePair',
        ),
    ]
