# Generated by Django 2.1.5 on 2019-01-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0008_auto_20190116_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_fields',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskfield',
            name='value',
        ),
        migrations.AlterUniqueTogether(
            name='abstractvalue',
            unique_together={('record', 'field')},
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskField',
        ),
    ]
