# Generated by Django 2.1.7 on 2019-03-13 15:29

from django.db import migrations, models
import django.db.models.deletion
import relativity.fields
import relativity.treebeard


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descendants',
            field=relativity.treebeard.MP_Descendants(default=1, from_fields=[], on_delete=django.db.models.deletion.DO_NOTHING, predicate=models.Q(('path__ne', relativity.fields.L('path')), ('path__startswith', relativity.fields.L('path'))), related_name='ascendants', to='self', to_fields=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='subtree',
            field=relativity.treebeard.MP_Subtree(default=1, from_fields=[], on_delete=django.db.models.deletion.DO_NOTHING, predicate=models.Q(path__startswith=relativity.fields.L('path')), related_name='rootpath', to='self', to_fields=[]),
            preserve_default=False,
        ),
    ]
