# Generated by Django 2.1.5 on 2019-03-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0009_auto_20190313_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eigenschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='modeldefinition.Category')),
            ],
            options={
                'verbose_name_plural': 'eigenschaften',
            },
        ),
    ]
