# Generated by Django 2.1.7 on 2019-03-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldefinition', '0010_eigenschaft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descendants',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subtree',
        ),
    ]
